services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d agents"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: